Repository Rhythm-Finders/pet-cast, pull requests merged in 2024-09, with the labels that each got.

#20 [Pull-Request] Gather-06
  backend/build.gradle
  backend/src/main/java/com/varchar6/petcast/config/AppConfig.java
  backend/src/main/java/com/varchar6/petcast/domain/gather.http
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/controller/GatherController.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/request/RequestCreateGatherDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/request/RequestDeactiveGatherDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/request/RequestDeleteMemberDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/request/RequestInvitationDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/request/RequestSendInvitationDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/request/RequestUpdateGatherInfoDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/response/ResponseCreateGatherDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/response/ResponseDeactiveGatherDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/response/ResponseDeleteMemberDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/response/ResponseInvitationDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/response/ResponseSendInvitaionDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/dto/response/ResponseUpdateGatherInfoDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/service/GatherService.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/service/GatherServiceImpl.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/domain/aggregate/GatherRole.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/domain/aggregate/entity/Gather.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/domain/aggregate/entity/GatherMember.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/domain/aggregate/entity/Invitation.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/domain/repository/GatherMemberRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/domain/repository/GatherRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/domain/repository/InvitationRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/query/controller/GatherController.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/query/dto/GatherDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/query/dto/GatherDetailDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/query/mapper/GatherMapper.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/query/service/GatherService.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/query/service/GatherServiceImpl.java
  backend/src/main/resources/com/varchar6/petcast/domain/gather/query/mapper/GatherMapper.xml
  backend/src/test/java/com/varchar6/petcast/domain/gather/command/application/service/GatherServiceImplTests.java
  backend/src/test/java/com/varchar6/petcast/domain/gather/query/service/GatherServiceImplTests.java
Labels: structure

#31 Feat/member 01 company
  backend/src/main/java/com/varchar6/petcast/domain/company/command/application/controller/CompanyController.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/application/controller/vo/request/EnrollRequestVO.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/application/controller/vo/response/CompanyResponseVO.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/application/dto/request/CompanyEnrollRequestDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/application/dto/response/CompanyResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/application/service/CompanyService.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/application/service/CompanyServiceImpl.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/domain/aggregate/Category.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/domain/aggregate/CategoryPK.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/domain/aggregate/Company.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/domain/repository/CategoryRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/company/command/domain/repository/CompanyRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/controller/CompanyController.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/dto/CategoryResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/dto/response/CompanyResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/mapper/CompanyMapper.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/service/CompanyService.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/service/CompanyServiceImpl.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/service/vo/CategoryVO.java
  backend/src/main/java/com/varchar6/petcast/domain/company/query/service/vo/CompanyVO.java
  backend/src/main/resources/com/varchar6/petcast/domain/company/query/mapper/CompanyMapper.xml
  backend/src/test/java/com/varchar6/petcast/domain/company/command/application/service/CompanyServiceTests.java
  backend/src/test/java/com/varchar6/petcast/domain/company/query/service/CompanyServiceTests.java
Labels: structure

#30 [Pull-Request] Request-02
  backend/src/main/java/com/varchar6/petcast/domain/request/command/application/controller/RequestsController.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/application/dto/request/CreateRequestsRequestDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/application/dto/response/CreateRequestsResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/application/service/RequestsService.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/application/service/RequestsServiceImpl.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/domain/aggregate/EventsStatus.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/domain/aggregate/RequestsStatus.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/domain/aggregate/entity/Event.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/domain/aggregate/entity/Requests.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/domain/repository/EventsRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/request/command/domain/repository/RequestsRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/controller/RequestsController.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/dto/CompanyAndRequestDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/dto/MemberAndRequestDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/dto/RequestDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/dto/RequestDetailDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/dto/RequestStatus.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/mapper/RequestsMapper.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/service/RequestsService.java
  backend/src/main/java/com/varchar6/petcast/domain/request/query/service/RequestsServiceImpl.java
  backend/src/main/resources/com/varchar6/petcast/domain/request/query/mapper/RequestsMapper.xml
Labels: structure

#34 [Pull-Request] Hotfix/gather-06
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/controller/GatherController.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/command/application/service/GatherServiceImpl.java
  backend/src/main/java/com/varchar6/petcast/domain/gather/query/service/GatherServiceImpl.java
Labels: invalid

#40 [Pull-Request] Domain-03 견적서 쿼리
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/controller/EstimateController.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/EstimateDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/EstimateProposalDTO1.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/EstimateProposalDTO2.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/EstimateStatus.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/ProposalDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/ProposalStatus.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/mapper/EstimatesMapper.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/service/EstimateService.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/service/EstimateServiceImpl.java
  backend/src/main/resources/com/varchar6/petcast/domain/proposalandestimate/query/mapper/EstimatesMapper.xml
  backend/src/main/resources/com/varchar6/petcast/domain/request/query/mapper/RequestsMapper.xml
  backend/src/test/java/com/varchar6/petcast/domain/company/query/service/CompanyServiceTests.java
Labels: structure

#41 [Pull-Request] Proposal&Estimate-03
  .idea/dataSources.local.xml
  .idea/dataSources/0b379daf-2541-4e8f-83f4-c82d2a960772.xml
  .idea/dataSources/0b379daf-2541-4e8f-83f4-c82d2a960772/storage_v2/_src_/schema/pet_cast.X160HA.meta
  .idea/dataSources/81149237-eb85-4c23-b7b2-36797ebc4bf0.xml
  .idea/workspace.xml
  backend/build.gradle
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/application/controller/EstimatesController.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/application/controller/ProposalsController.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/application/dto/EstimatesRequestDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/application/dto/EstimatesResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/application/dto/ProposalsRequestDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/application/dto/ProposalsResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/domain/aggregate/Estimates.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/domain/aggregate/EstimatesStatus.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/domain/aggregate/Proposals.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/domain/aggregate/ProposalsStatus.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/domain/repository/EstimatesRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/domain/repository/ProposalsRepository.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/service/EstimatesService.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/service/EstimatesServiceImpl.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/service/ProposalsService.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/command/service/ProposalsServiceImpl.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/controller/ProposalController.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/EstimateResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/dto/ProposalResponseDTO.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/mapper/ProposalsMapper.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/service/ProposalService.java
  backend/src/main/java/com/varchar6/petcast/domain/proposalandestimate/query/service/ProposalServiceImpl.java
  backend/src/main/resources/com/varchar6/petcast/domain/proposalandestimate/query/mapper/ProposalsMapper.xml
  backend/src/main/resources/com/varchar6/petcast/domain/request/reporitory/RequestMapper.xml
  backend/src/test/java/com/varchar6/petcast/domain/proposalandestimate/command/service/EstimatesServiceImplTests.java
  backend/src/test/java/com/varchar6/petcast/domain/proposalandestimate/command/service/ProposalsServiceTests.java
  backend/src/test/java/com/varchar6/petcast/domain/proposalandestimate/query/service/ProposalServiceTests.java
Labels: structure

#56 [Domain-06 Gather] ExceptionHandler & Refactoring
  backend/service-configuration/src/main/resources/application.yml
  backend/service-gateway/src/main/resources/application.yml
  backend/service-member/src/main/resources/application.yml
  backend/service-others/build.gradle
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/ServiceOthersApplication.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/common/exception/CommonException.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/common/exception/ErrorCode.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/common/exception/ExceptionResponse.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/common/exception/GlobalExceptionHandler.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/config/FeignClientConfig.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/gather/command/application/controller/GatherController.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/gather/command/application/dto/request/RequestInvitationDTO.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/gather/command/application/service/GatherServiceImpl.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/gather/command/domain/aggregate/entity/GatherMember.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/gather/command/domain/service/GatherServiceImpl.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/gather/query/controller/GatherController.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/gather/query/service/GatherServiceImpl.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/proposalandestimate/query/controller/EstimateController.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/request/query/controller/RequestsController.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/sms/controller/SmsController.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/sms/dto/request/RequestSendSms.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/sms/dto/response/ResponseSendSms.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/sms/service/SmsService.java
  backend/service-others/src/main/java/com/varchar6/petcast/serviceothers/domain/sms/service/SmsServiceImpl.java
  backend/service-others/src/main/resources/application.yml
  backend/service-others/src/main/resources/com/varchar6/petcast/serviceothers/domain/gather/query/mapper/GatherMapper.xml
Labels: enhancement

#65 Init/frontend structure
  frontend/src/App.vue
  frontend/src/assets/image/main/main_logo.png
  frontend/src/assets/image/profile/logo.png
  frontend/src/components/Footer.vue
  frontend/src/components/footer/FooterLeft.vue
  frontend/src/components/footer/FooterRight.vue
  frontend/src/components/header/Sample.vue
  frontend/src/components/navigation/Sample.vue
  frontend/src/router/index.js
  frontend/src/views/contents/About.vue
  frontend/src/views/contents/Home.vue
  frontend/src/views/footer/Footer.vue
  frontend/src/views/header/header/Header.vue
  frontend/src/views/header/navigation/Navigation.vue
Labels: structure

#100 [Front] 회원가입 기능 구현
  frontend/package.json
  frontend/src/assets/icon/signup/avatar.png
  frontend/src/js/data-temp.json
  frontend/src/router/index.js
  frontend/src/views/contents/Login.vue
  frontend/src/views/contents/signup/Signup.vue
Labels: structure

#102 [Front-end] HOTFIX PR 충돌 해결 도중 에러 발생 수정
  frontend/src/main.js
  frontend/src/router/index.js
Labels: bug

#105 Feat/front mypage details
  frontend/src/assets/image/19.png
  frontend/src/assets/image/event_profile.png
  frontend/src/assets/image/profile/dogi.png
  frontend/src/js/data-temp.json
  frontend/src/views/contents/my_page/MyPage.vue
  frontend/src/views/contents/my_page/PetProfileCard.vue
  frontend/src/views/contents/my_page/PetProfileCardList.vue
  frontend/src/views/contents/my_page/SectionItem.vue
  frontend/src/views/contents/my_page/SectionList.vue
  frontend/src/views/contents/my_page/custom_domain/EventList.vue
  frontend/src/views/contents/my_page/custom_domain/QnAList.vue
  frontend/src/views/contents/my_page/custom_domain/ReviewList.vue
  frontend/src/views/contents/my_page/custom_domain/item/EventItem.vue
  frontend/src/views/contents/my_page/custom_domain/item/QnAItem.vue
  frontend/src/views/contents/my_page/custom_domain/item/ReviewItem.vue
Labels: structure
